name: Send Metrics from JSON

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  send-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Read JSON and send metrics
        run: |
          # Path to your JSON file in root directory
          json_file="../metrics.json"

          # Check if JSON file exists
          if [ ! -f "$json_file" ]; then
            echo "Error: $json_file not found!"
            exit 1
          fi

          # Debug: show file contents
          echo "Contents of $json_file:"
          cat $json_file

          # Parse JSON fields with jq
          pr_id=$(jq -r '.labels.pr_id' $json_file)
          total=$(jq -r '.labels.total' $json_file)
          passed=$(jq -r '.labels.passed' $json_file)
          failed=$(jq -r '.labels.failed' $json_file)
          skipped=$(jq -r '.labels.skipped' $json_file)
          value=$(jq -r '.value' $json_file)

          # Show parsed values
          echo "Parsed values:"
          echo "PR ID: $pr_id"
          echo "Total: $total"
          echo "Passed: $passed"
          echo "Failed: $failed"
          echo "Skipped: $skipped"
          echo "Value: $value"

          # Construct the Prometheus metric string
          metric_name="test_summary_v1"
          metric="# HELP ${metric_name} A test metric\n# TYPE ${metric_name} counter\n${metric_name}{pr_id=\"${pr_id}\",total=\"${total}\",passed=\"${passed}\",failed=\"${failed}\",skipped=\"${skipped}\"} ${value}"

          # Debug: show the constructed metric
          echo "Constructed metric:"
          echo "$metric"

          # Save metric to file
          echo "$metric" > metric.txt

          # Send to Pushgateway (update URL accordingly)
          curl -X POST --data-binary @metric.txt http://your-pushgateway-url:9091/metrics/job/playwright_test
          
      - name: Done
        run: echo "Metrics sent!"
