name: Send Metrics to Grafana Cloud via Pushgateway

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  send-metrics:
    runs-on: ubuntu-latest

    env:
      METRIC_NAME: cmms_summary_test_v1

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl docker.io

      # Step 3: Extract test results from summary.json
      - name: Extract test results from summary.json
        id: extract-summary
        run: |
          if [ ! -f "summary.json" ]; then
            echo "summary.json not found."
            exit 1
          fi

          TOTAL=$(jq '.stats.tests // 0' summary.json)
          PASSED=$(jq '.stats.passes // 0' summary.json)
          FAILED=$(jq '.stats.failures // 0' summary.json)
          SKIPPED=$(jq '.stats.skipped // 0' summary.json)
          FLAKY=$(jq '[.results[] | select(.flaky == true)] | length' summary.json)

          echo "TOTAL=$TOTAL" >> $GITHUB_ENV
          echo "PASSED=$PASSED" >> $GITHUB_ENV
          echo "FAILED=$FAILED" >> $GITHUB_ENV
          echo "SKIPPED=$SKIPPED" >> $GITHUB_ENV
          echo "FLAKY=$FLAKY" >> $GITHUB_ENV

          echo "Test Summary - Total: $TOTAL, Passed: $PASSED, Failed: $FAILED, Skipped: $SKIPPED, Flaky: $FLAKY"

      # Step 4: Start Pushgateway container
      - name: Start Pushgateway
        run: |
          docker run -d --name pushgateway -p 9091:9091 prom/pushgateway:latest
          sleep 5

      # Step 5: Push metrics to Pushgateway
      - name: Push metrics to Pushgateway
        env:
          PR_ID: ${{ github.run_id }}
          PR_TITLE: ${{ github.workflow }}
          TOTAL: ${{ env.TOTAL }}
          PASSED: ${{ env.PASSED }}
          FAILED: ${{ env.FAILED }}
          SKIPPED: ${{ env.SKIPPED }}
          FLAKY: ${{ env.FLAKY }}
          VALUE: ${{ env.FAILED }}
        run: |
          cat <<EOF | curl --data-binary @- http://localhost:9091/metrics/job/test_metrics/pr_id/${PR_ID}/pr_title/${PR_TITLE}
          # TYPE $METRIC_NAME gauge
          $METRIC_NAME{type="total"} $TOTAL
          $METRIC_NAME{type="passed"} $PASSED
          $METRIC_NAME{type="failed"} $FAILED
          $METRIC_NAME{type="skipped"} $SKIPPED
          $METRIC_NAME{type="flaky"} $FLAKY
          EOF

      # Step 6: Create Prometheus config
      - name: Create Prometheus config
        run: |
          cat > prometheus.yml <<EOF
          global:
            scrape_interval: 15s
            evaluation_interval: 15s

          scrape_configs:
            - job_name: 'pushgateway'
              honor_labels: true
              static_configs:
                - targets: ['localhost:9091']

          remote_write:
            - url: "${GRAFANA_CLOUD_URL}"
              basic_auth:
                username: "${GRAFANA_CLOUD_USER}"
                password: "${GRAFANA_CLOUD_API_KEY}"
          EOF

          cat prometheus.yml
        env:
          GRAFANA_CLOUD_URL: ${{ secrets.GRAFANA_CLOUD_URL }}
          GRAFANA_CLOUD_USER: ${{ secrets.GRAFANA_CLOUD_USER }}
          GRAFANA_CLOUD_API_KEY: ${{ secrets.GRAFANA_CLOUD_API_KEY }}

      # Step 7: Start Prometheus
      - name: Start Prometheus
        run: |
          docker run -d --name prometheus --network host \
            -v $(pwd)/prometheus.yml:/etc/prometheus/prometheus.yml \
            prom/prometheus:latest \
            --config.file=/etc/prometheus/prometheus.yml \
            --web.enable-lifecycle

          echo "Waiting for Prometheus to scrape and forward metrics..."
          sleep 30
          docker logs prometheus

      # Step 8: Verify metrics
      - name: Verify Prometheus Metrics
        run: |
          curl -s http://localhost:9090/api/v1/targets | jq .

          RESULT=$(curl -s "http://localhost:9090/api/v1/query?query=${METRIC_NAME}" | jq -r '.data.result | length')

          if [ "$RESULT" -gt 0 ]; then
            echo "✅ Metrics are available in Prometheus"
            curl -s "http://localhost:9090/api/v1/query?query=${METRIC_NAME}" | jq .
          else
            echo "❌ Metrics not found in Prometheus"
            exit 1
          fi

      # Step 9: Cleanup
      - name: Clean up containers
        if: always()
        run: |
          docker stop prometheus pushgateway || true
          docker rm prometheus pushgateway || true
