name: Test Grafana Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ExtractAndUpload:
    runs-on: ubuntu-latest
    env:
      METRIC_NAME: tung_summary_v1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Convert Mocha-style summary.json to flat metrics
        run: |
          INPUT_FILE=summary.json
          OUTPUT_FILE=converted-metrics.json

          if [ ! -f "$INPUT_FILE" ]; then
            echo "$INPUT_FILE not found"
            exit 1
          fi

          TOTAL=$(jq '.stats.tests // 0' "$INPUT_FILE")
          PASSED=$(jq '.stats.passes // 0' "$INPUT_FILE")
          FAILED=$(jq '.stats.failures // 0' "$INPUT_FILE")
          SKIPPED=$(jq '.stats.skipped // 0' "$INPUT_FILE")
          FLAKY=$(jq '[.results[] | select(.flaky == true)] | length' "$INPUT_FILE")

          jq -n \
            --argjson tests "$TOTAL" \
            --argjson passed "$PASSED" \
            --argjson failed "$FAILED" \
            --argjson skipped "$SKIPPED" \
            --argjson flaky "$FLAKY" \
            '{
              tests: $tests,
              passed: $passed,
              failed: $failed,
              skipped: $skipped,
              flaky: $flaky
            }' > "$OUTPUT_FILE"

          echo "✅ Converted to $OUTPUT_FILE"
          cat "$OUTPUT_FILE"

      - name: Upload test summary artifact
        uses: actions/upload-artifact@v4
        with:
          name: summary-json
          path: converted-metrics.json
